[profile.default]
src = "src"
out = "out"
libs = ["lib"]
exclude = ["script/DeployAnvil.s.sol", "script/VerifyUser.s.sol"]
via_ir = true
optimizer = true
optimizer_runs = 200

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin-upgradeable/contracts/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
